[build]
publish = "dist"
command = "npx vite build"

[build.environment]
VITE_SUPABASE_URL = "https://ojwepowksnbmbcgnokve.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qd2Vwb3drc25ibWJjZ25va3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMTc4NjAsImV4cCI6MjA4Njg5Mzg2MH0.C8Tweqtevl0cNoi9hCZ-dT_9vGRB5D2V4gBM5Lbv0r0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context]
[context.production]
[context.production.environment]
VITE_SUPABASE_URL = "https://ojwepowksnbmbcgnokve.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qd2Vwb3drc25ibWJjZ25va3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMTc4NjAsImV4cCI6MjA4Njg5Mzg2MH0.C8Tweqtevl0cNoi9hCZ-dT_9vGRB5D2V4gBM5Lbv0r0"

[context.deploy-preview]
[context.deploy-preview.environment]
VITE_SUPABASE_URL = "https://ojwepowksnbmbcgnokve.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qd2Vwb3drc25ibWJjZ25va3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMTc4NjAsImV4cCI6MjA4Njg5Mzg2MH0.C8Tweqtevl0cNoi9hCZ-dT_9vGRB5D2V4gBM5Lbv0r0"

[context.branch-deploy]
[context.branch-deploy.environment]
VITE_SUPABASE_URL = "https://ojwepowksnbmbcgnokve.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qd2Vwb3drc25ibWJjZ25va3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMTc4NjAsImV4cCI6MjA4Njg5Mzg2MH0.C8Tweqtevl0cNoi9hCZ-dT_9vGRB5D2V4gBM5Lbv0r0"